version: "2.0"

services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ".:/var/www/html:ro"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php

    php:
        image: cyberduck/php-fpm-laravel:7.2
        expose:
            - 9000
        volumes:
            - ".:/var/www/html"
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306 
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tournament
            MYSQL_USER: root
            MYSQL_PASSWORD: root
volumes:
    db_data:
